title: "Your Blog Title"
description: "Description of your blog"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # the base hostname & protocol for your site

# Remove or comment out the theme
# theme: minima

plugins:
  - jekyll-feed

markdown: kramdown
